name: Deploy FastAPI to Oracle VM

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'  # 백엔드 코드 변경 시 실행
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Backend to Oracle VM
      run: |
        ssh -v -o StrictHostKeyChecking=no dio@192.168.56.1 'bash -s' << 'EOF'          
               export SUDO_PASSWORD="${{ secrets.SUDO_PASSWORD }}"
         /mindsync/deploy_back.sh  # 빌드 및 배포 스크립트를 실행.
        EOF
